---
title: "reading_data_from_the_web"
author: "Diana Ballesteros Gonzalez"
date: "10/11/2018"
output: github_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Scrape a table 
First get the HTML 
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

drug_use_xml
```

Get the tables from the html 
```{r}

## Allows you to extract the tables 
drug_use_xml %>%
  html_nodes(css = "table")

## Allows you to extract the first table only 
drug_use_xml %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table() 

## Slice let's you access rows by number (-1 removes the first row)
drug_use_xml %>%
  html_nodes(css = "table") %>% 
  .[[2]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

## Learning Assessment 
```{r}
## Header = TRUE allows you to keep the header 
nyc_cost_xml = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table(header = TRUE) 
```

## Harry Potter: CSS Selectors 
```{r}
## For each element, I’ll use the CSS selector in html_nodes() to extract the relevant HTML code, and convert it to text. Then I can combine these into a data frame.

## Load in the data 
hpsaga_html = read_html("https://www.imdb.com/list/ls000630791/") 

## Add as_tible() to export as a table 
title_vec = hpsaga_html %>%
  html_nodes(css = ".lister-item-header a") %>% 
  html_text() 

gross_rev_vec = hpsaga_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()
  
runtime_vec = hpsaga_html %>%
  html_nodes(".runtime") %>%
  html_text() 

hpsaga_df = tibble(
  title = title_vec,
  rev = gross_rev_vec,
  runtime = runtime_vec
)
```

## Learning Assessment
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```

## Using an API
```{r}
## Get the NYC Data - Water Consumption as .csv
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")
```

As JSON
```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

BRFSS 2010
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

```{r}
poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name

poke$height

poke$abilities
```

